--
-- PostgreSQL database dump
--

-- Dumped from database version 14.3
-- Dumped by pg_dump version 14.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    id integer NOT NULL,
    balance integer,
    amount integer
);


ALTER TABLE public.account OWNER TO postgres;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: operations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.operations (
    operation_id integer NOT NULL,
    account_id integer NOT NULL,
    operation_type integer,
    amount integer,
    operation_time timestamp without time zone,
    operation_date date
);


ALTER TABLE public.operations OWNER TO postgres;

--
-- Name: operations_operation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.operations ALTER COLUMN operation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.operations_operation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account (id, balance, amount) FROM stdin;
8	92365	0
7	37061	0
1	10000	0
10	9880	0
2	297566	0
9	88320	0
\.


--
-- Data for Name: operations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.operations (operation_id, account_id, operation_type, amount, operation_time, operation_date) FROM stdin;
4	8	1	555	2022-06-24 13:58:52.01549	2022-06-24
5	8	1	555	2022-06-24 13:58:53.854328	2022-06-24
6	7	2	1200	2022-06-24 14:05:10.407887	2022-06-24
1	8	1	555	2022-06-22 13:58:36.58431	2022-06-24
7	7	2	1200	2022-06-24 14:19:30.536456	2022-06-24
2	7	2	1200	2022-06-22 13:58:40.578038	2022-06-22
3	7	2	1200	2022-06-23 13:58:48.954461	2022-06-23
8	7	2	1200	2022-06-24 14:23:58.235499	2022-06-24
9	8	1	555	2022-06-24 14:24:11.100709	2022-06-24
10	7	1	555	2022-06-24 14:24:18.478585	2022-06-24
11	7	1	555	2022-06-24 14:24:20.458965	2022-06-24
12	7	2	1200	2022-06-24 14:24:26.850529	2022-06-24
13	7	2	1200	2022-06-24 14:24:28.88075	2022-06-24
\.


--
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 10, true);


--
-- Name: operations_operation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.operations_operation_id_seq', 13, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: operations operations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_pkey PRIMARY KEY (operation_id);


--
-- Name: operations operations_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.operations
    ADD CONSTRAINT operations_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.account(id);


--
-- PostgreSQL database dump complete
--

